<a href="https://colab.research.google.com/github/deyimmah-crypto/my-assignment/blob/main/Copy_of_Untitled6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
# 1. Create a dictionary with 5 products as keys and their stock quantities as values
products = {
    'Laptop': 15,
    'Mouse': 50,
    'Keyboard': 20,
    'Monitor': 10,
    'Webcam': 5
}
print("Initial Inventory:")
print(products)
print("\n")

# 2. Add a new product and update the quantity of an existing one
products['Headphones'] = 30  # Add a new product
products['Mouse'] = 45       # Update existing product quantity
print("Inventory after adding new product and updating an existing one:")
print(products)
print("\n")

# 3. Write a function to return products with stock less than 10
def get_low_stock_products(inventory_dict):
    low_stock = {}
    for product, quantity in inventory_dict.items():
        if quantity < 10:
            low_stock[product] = quantity
    return low_stock

low_stock_items = get_low_stock_products(products)
print("Products with stock less than 10:")
print(low_stock_items)
print("\n")

# 4. Delete a discontinued product and display the updated dictionary
del products['Webcam'] # Delete the discontinued product 'Webcam'
print("Inventory after deleting 'Webcam':")
print(products)
print("\n")

# 5. Use .items() to loop through and print each product with its quantity
print("Current Product Inventory (using .items()):")
for product, quantity in products.items():
    print(f"{product}: {quantity}")

Initial Inventory:
{'Laptop': 15, 'Mouse': 50, 'Keyboard': 20, 'Monitor': 10, 'Webcam': 5}


Inventory after adding new product and updating an existing one:
{'Laptop': 15, 'Mouse': 45, 'Keyboard': 20, 'Monitor': 10, 'Webcam': 5, 'Headphones': 30}


Products with stock less than 10:
{'Webcam': 5}


Inventory after deleting 'Webcam':
{'Laptop': 15, 'Mouse': 45, 'Keyboard': 20, 'Monitor': 10, 'Headphones': 30}


Current Product Inventory (using .items()):
Laptop: 15
Mouse: 45
Keyboard: 20
Monitor: 10
Headphones: 30


In [ ]:
import numpy as np

transactions = np.array([
    [1200, 1350, 1600, 1450, 1700, 1800],   # Branch 1
    [1000, 1100, 1150, 1200, 1300, 1250],   # Branch 2
    [900,  950,  1000, 1050, 1100, 1200],   # Branch 3
    [1500, 1600, 1700, 1650, 1750, 1900]    # Branch 4
])

print("Transaction Volume Array (4 branches × 6 months):")
print(transactions)

branch_totals = np.sum(transactions, axis=1)
print("Total Transactions Per Branch:")
print(branch_totals)

highest_branch_index = np.argmax(branch_totals)
print(f"Branch with Highest Transactions: Branch {highest_branch_index + 1}")

average_volume = np.mean(transactions)
print("Average Monthly Transaction Volume Across All Branches:")
print(average_volume)

reshaped = transactions.reshape(3, 8)

print("Reshaped Array (3 × 8):")
print(reshaped)

print("\nImplications of Reshaping:")
print("- The data values remain the same, but their positions change.")
print("- Reshaping does NOT combine, delete, or modify values; it only reorganizes them.")
print("- The new shape must contain the same total number of elements (4×6 = 24 = 3×8).")

Transaction Volume Array (4 branches × 6 months):
[[1200 1350 1600 1450 1700 1800]
 [1000 1100 1150 1200 1300 1250]
 [ 900  950 1000 1050 1100 1200]
 [1500 1600 1700 1650 1750 1900]]
Total Transactions Per Branch:
[ 9100  7000  6200 10100]
Branch with Highest Transactions: Branch 4
Average Monthly Transaction Volume Across All Branches:
1350.0
Reshaped Array (3 × 8):
[[1200 1350 1600 1450 1700 1800 1000 1100]
 [1150 1200 1300 1250  900  950 1000 1050]
 [1100 1200 1500 1600 1700 1650 1750 1900]]

Implications of Reshaping:
- The data values remain the same, but their positions change.
- Reshaping does NOT combine, delete, or modify values; it only reorganizes them.
- The new shape must contain the same total number of elements (4×6 = 24 = 3×8).


### Exercise 2: Lists in Logistics Management (Supply Chain Sector)

**Topic:** Python Lists (Marks: 20)

**Scenario:** A logistics company tracks delivery routes and package counts.

**Task:**
1.  Create a list of 10 delivery routes, each represented as a string. (4 marks)
2.  Append a new route and remove a discontinued one. (4 marks)
3.  Sort the list alphabetically and reverse it. (4 marks)
4.  Count how many routes start with the letter “N”. (4 marks)
5.  Use list comprehension to create a new list of routes longer than 15 characters. (4 marks)

In [15]:
# 1. Create a list of 10 delivery routes, each represented as a string
routes = [
    'NorthStar Transport',
    'SouthCargo Route',
    'EastFlow Movers',
    'WestBridge Logistics',
    'CentralHub Logistics',
    'SkyTrack Freight',
    'RapidShift Delivery',
    'Oceanic Express',
    'National Carrier Path',
    'Global Connect'
]
print("Initial Delivery Routes:")
print(routes)
print("\n")

# 2. Append a new route and remove a discontinued one
routes.append('MegaRoute Express')  # Append a new route
routes.remove('Oceanic Express')     # Remove a discontinued route
print("Routes after adding and removing:")
print(routes)
print("\n")

# 3. Sort the list alphabetically and reverse it
routes.sort() # Sort alphabetically
routes.reverse() # Reverse the sorted list
print("Routes sorted alphabetically and then reversed:")
print(routes)
print("\n")

# 4. Count how many routes start with the letter “N”
count_N = 0
for route in routes:
    if route.startswith('N'):
        count_N += 1
print(f"Number of routes starting with 'N': {count_N}")
print("\n")

# 5. Use list comprehension to create a new list of routes longer than 15 characters
long_routes = [route for route in routes if len(route) > 15]
print("Routes longer than 15 characters (using list comprehension):")
print(long_routes)

Initial Delivery Routes:
['NorthStar Transport', 'SouthCargo Route', 'EastFlow Movers', 'WestBridge Logistics', 'CentralHub Logistics', 'SkyTrack Freight', 'RapidShift Delivery', 'Oceanic Express', 'National Carrier Path', 'Global Connect']


Routes after adding and removing:
['NorthStar Transport', 'SouthCargo Route', 'EastFlow Movers', 'WestBridge Logistics', 'CentralHub Logistics', 'SkyTrack Freight', 'RapidShift Delivery', 'National Carrier Path', 'Global Connect', 'MegaRoute Express']


Routes sorted alphabetically and then reversed:
['WestBridge Logistics', 'SouthCargo Route', 'SkyTrack Freight', 'RapidShift Delivery', 'NorthStar Transport', 'National Carrier Path', 'MegaRoute Express', 'Global Connect', 'EastFlow Movers', 'CentralHub Logistics']


Number of routes starting with 'N': 2


Routes longer than 15 characters (using list comprehension):
['WestBridge Logistics', 'SouthCargo Route', 'SkyTrack Freight', 'RapidShift Delivery', 'NorthStar Transport', 'National Carrier Path'

### Explanation: Why Tuples are Suitable for Storing Patient Vitals (Task 3)

Tuples are ideal for storing patient vitals because:

*   **Immutability:** Once created, the elements of a tuple cannot be changed. This is crucial for medical records where data integrity is paramount. You wouldn't want a patient's recorded vitals to be accidentally altered.
*   **Data Integrity:** The immutability ensures that a specific set of vitals (like blood pressure and heart rate taken at a particular time) remains constant as an unchangeable record.
*   **Ordered Collection:** Tuples maintain the order of elements, which is important for consistently representing vital signs (e.g., always knowing the heart rate is the fourth element).
*   **Heterogeneous Data:** Tuples can store different data types (e.g., string for name, integer for age, float for blood pressure), which is necessary for patient vital records.
*   **Read-Only Access:** They are optimized for read-only operations, making them efficient for retrieving historical vital records.

In [14]:
# 1. Create a tuple for a patient containing: (Name, Age, BloodPressure, HeartRate)
patient_vitals = ("Alice Smith", 34, "120/80", 72)
print(f"Patient Vitals Tuple: {patient_vitals}")
print("\n")

# 2. Access and print the patient's age and heart rate
patient_age = patient_vitals[1]    # Age is at index 1
patient_heart_rate = patient_vitals[3] # HeartRate is at index 3
print(f"Patient's Age: {patient_age}")
print(f"Patient's Heart Rate: {patient_heart_rate}")
print("\n")

# 4. Convert the tuple to a list, update the heart rate, and convert it back to a tuple
print(f"Original Heart Rate: {patient_vitals[3]}")
patient_vitals_list = list(patient_vitals)
patient_vitals_list[3] = 76 # Update heart rate
patient_vitals_updated = tuple(patient_vitals_list)
print(f"Updated Patient Vitals Tuple (after heart rate change): {patient_vitals_updated}")
print("\n")

# 5. Create a tuple of 5 patients and write code to extract all names
all_patients_vitals = (
    ("Alice Smith", 34, "120/80", 72),
    ("Bob Johnson", 52, "130/85", 78),
    ("Charlie Brown", 28, "115/75", 68),
    ("Diana Prince", 41, "125/82", 75),
    ("Eve Adams", 60, "140/90", 80)
)

print("All Patient Vitals (Tuple of Tuples):")
for patient in all_patients_vitals:
    print(patient)
print("\n")

patient_names = [patient[0] for patient in all_patients_vitals]
print(f"Extracted Patient Names: {patient_names}")

Patient Vitals Tuple: ('Alice Smith', 34, '120/80', 72)


Patient's Age: 34
Patient's Heart Rate: 72


Original Heart Rate: 72
Updated Patient Vitals Tuple (after heart rate change): ('Alice Smith', 34, '120/80', 76)


All Patient Vitals (Tuple of Tuples):
('Alice Smith', 34, '120/80', 72)
('Bob Johnson', 52, '130/85', 78)
('Charlie Brown', 28, '115/75', 68)
('Diana Prince', 41, '125/82', 75)
('Eve Adams', 60, '140/90', 80)


Extracted Patient Names: ['Alice Smith', 'Bob Johnson', 'Charlie Brown', 'Diana Prince', 'Eve Adams']
